---
title: "4. Træer"
author: "Anders Thor Kellmer"
date: "2023-06-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```

Load dependencies and set seed.

```{r, message=FALSE}
library(dplyr)       
library(e1071)       
library(caret)       
library(rpart)      
library(rpart.plot)
library(ipred)       
set.seed(123)
```
Import data.

```{r}
data("airquality")
str(airquality)
```

Fit tree.

```{r}
tree = rpart(
  formula = Ozone ~ .,
  data = airquality, 
  control = rpart.control(minsplit = 2, cp = 0.001)
)
printcp(tree)
```

Get the best model.

```{r}
pruned.tree = tree$cptable[which.min(tree$cptable[,"xerror"]),"CP"] %>%
  prune(tree, cp = .)
printcp(pruned.tree)
prp(pruned.tree, faclen = 0, extra = 1, roundint = F, digits = 5)
```


Make prediction.

```{r}
data.frame(Solar.R = 150, Wind = 8, Temp = 70, Month = 5, Day = 5) %>%
  predict(pruned.tree, .)
```


Perform bagging.

```{r}
bag = bagging(
  formula = Ozone ~ .,
  data = airquality,
  nbagg = 150,   
  coob = TRUE,
  control = rpart.control(minsplit = 2, cp = 0.001)
)
bag
```
Determine variance importance.

```{r var imp}
var.imp = data.frame(var = names(airquality[,-1]), imp=varImp(bag)) %>%
  .[order(.$Overall, decreasing = TRUE), ]

barplot(
  var.imp$Overall,
  names.arg = rownames(var.imp),
  horiz = FALSE,
  xlab = "Variable Importance"
  ) %>%
  text(
    y = 0,
    labels = round(var.imp$Overall, 1), 
    cex = 1, 
    pos = 3)
```
Make prediction.

```{r pred}
data.frame(Solar.R = 150, Wind = 8, Temp = 70, Month = 5, Day = 5) %>%
  predict(bag, .)

```
